// frontend/react/src/App.tsx
import { useState } from "react";
import SignupForm from "./SignupForm";

function App() {
	const [form, setForm] = useState(new SignupForm());

	function reload (fn: any) {
		if (fn) fn();
		setForm(clone(form));
	}

	return (
		<div>
			<div>
				<button className="button-fill" onClick={() => reload(() => form.fill() ) }>Fill</button>
			</div>
			<div>
				<span className="span-step">{ form.step }</span>
			</div>
			<div>
				<span className="span-progress">{ form.getProgress() }%</span>
			</div>
			<div>
				<span className="span-success">{ form.success }</span>
			</div>
			<div>
				<span className="span-error">{ form.error }</span>
			</div>
			{ form.step === 1 && <div>
				<input className="input-is-passenger" type="checkbox" checked={form.isPassenger} onChange={(e) => reload(() => form.isPassenger = e.target.checked ) } />
			</div> }
			{ form.step === 2 && <div>
				<input className="input-name" value={form.name} onChange={(e) => reload(() => form.name = e.target.value ) }/>
				<input className="input-email" value={form.email} onChange={(e) => reload(() => form.email = e.target.value ) }/>
				<input className="input-cpf" value={form.cpf} onChange={(e) => reload(() => form.cpf = e.target.value ) }/>
			</div> }
			{ form.step === 3 && <div>
				<input className="input-password" value={form.password} onChange={(e) => reload(() => form.password = e.target.value ) }/>
				<input className="input-confirm-password" value={form.confirmPassword} onChange={(e) => reload(() => form.confirmPassword = e.target.value ) }/>
			</div> }
			<div>
				{ form.step > 1 && <button className="button-previous" onClick={() => reload(() => form.previous() ) }>Previous</button> }
				{ form.step < 3 && <button className="button-next" onClick={() => reload(() => form.next() ) }>Next</button> }
				{ form.step === 3 && <button className="button-confirm" onClick={() => reload(() => form.confirm() ) }>Confirm</button> }
			</div>
		</div>
	)
}

function clone(obj: any) {
	var copy = new obj.constructor;
	for (var attr in obj) {
		if (obj.hasOwnProperty(attr)) copy[attr] = obj[attr];
	}
	return copy;
}

export default App

// frontend/vue/src/App.vue
<script setup lang="ts">
	import { ref, inject } from "vue";
	import AccountGateway, { AccountGatewayHttp } from "./infra/gateway/AccountGateway";
	import SignupForm from "./entity/SignupForm";

	const accountGateway = inject("accountGateway") as AccountGateway;

	let form = ref(new SignupForm());

	form.value.register("confirmed", async function (event: any) {
		await accountGateway.signup(event);
		form.value.success = "OK";
	});
	
</script>

<template>
	<div>
		<div>
			<button class="button-fill" @click="form.fill()">Fill</button>
		</div>
		<div>
			<span class="span-step">Step {{ form.step }}</span>
		</div>
		<div>
			<span class="span-progress">{{ form.getProgress() }}%</span>
		</div>
		<div>
			<span v-if="form.success" class="span-success">{{ form.success }}</span>
		</div>
		<div>
			<span v-if="form.error" class="span-error">{{ form.error }}</span>
		</div>
		<div v-if="form.step === 1">
			<div>
				<input class="input-is-passenger" type="checkbox" v-model="form.isPassenger"/>
			</div>
		</div>
		<div v-if="form.step === 2">
			<div>
				<input class="input-name" type="text" v-model="form.name" placeholder="Name"/>
			</div>
			<div>
				<input class="input-email" type="text" v-model="form.email" placeholder="Email"/>
			</div>
			<div>
				<input class="input-cpf" type="text" v-model="form.cpf" placeholder="Cpf"/>
			</div>
		</div>
		<div v-if="form.step === 3">
			<div>
				<input class="input-password" type="text" v-model="form.password" placeholder="Password"/>
			</div>
			<div>
				<input class="input-confirm-password" type="text" v-model="form.confirmPassword" placeholder="Confirm password"/>
			</div>
		</div>
		<div>
			<button v-if="form.step > 1" class="button-previous" @click="form.previous()">Previous</button>
			<button v-if="form.step < 3" class="button-next" @click="form.next()">Next</button>
			<button v-if="form.step === 3" class="button-confirm" @click="form.confirm()">Confirm</button>
		</div>
	</div>
</template>

<style>
</style>
